### ISSUE TITLE
rdirichlet_mat 

### ISSUE THREAD

**Issue by oliver-diaz** [hesim-dev/hesim#12]
It seems that on R 3.6 the hesim function rdirichlet_mat has a conflict with the R package data.table.
**

> Error in hesim::rdirichlet_mat(n, mat) : 
>   The number of rows of 'alpha' must be less than or equal to the number of columns.

old 
**

previous versions run fine. Here is the difference between the old and new version of the rdirichlet_mat function

> function (n, alpha) 
> {
>     if (n <= 0) {
>         stop("n must be greater than 0")
>     }
>     if (!is.matrix(alpha) & !is.vector(alpha)) {
>         stop("alpha must be a vector or a matrix")
>     }
>     if (is.vector(alpha)) {
>         alpha <- matrix(alpha, nrow = 1)
>     }
>     samp <- C_rdirichlet_mat(n, alpha)
>     return(samp)
> }
> <bytecode: 0x6bdca78>
> <environment: namespace:hesim>

** 

new

> function (n, alpha, output = c("array", "matrix", "data.frame", 
>     "data.table")) 
> {
>     output <- match.arg(output)
>     if (n <= 0) {
>         stop("n must be greater than 0")
>     }
>     if (!(is.numeric(alpha) & length(dim(alpha)) <= 2)) {
>         stop("alpha must be a numeric matrix or vector")
>     }
>     if (!is.matrix(alpha)) {
>         alpha <- matrix(alpha, nrow = 1)
>     }
>     if (nrow(alpha) > ncol(alpha)) {
>         stop(paste0("The number of rows of 'alpha' must be less than or equal to ", 
>             "the number of columns."))
>     }
>     samp <- C_rdirichlet_mat(n, alpha)
>     if (output %in% c("matrix", "data.frame", "data.table")) {
>         samp <- matrix(c(aperm(samp, perm = c(2, 1, 3))), ncol = dim(samp)[1] * 
>             dim(samp)[2], byrow = TRUE)
>         colnames(samp) <- paste0("prob_", 1:ncol(samp))
>     }
>     if (output == "data.frame") {
>         samp <- data.frame(samp)
>     }
>     if (output == "data.table") {
>         samp <- data.table(samp)
>     }
>     return(samp)
> }
> <bytecode: 0x7f8f479bea50>
> <environment: namespace:hesim>

**Comment by dincerti** [comment]
Hi Oliver,

The error message is intended with the updated function. It appears you are trying simulate values in a case where there are more rows than columns in 'alpha'. Is there a reason you are trying to do this? 'alpha' is meant to be a matrix where rows are transitions from a state and columns are transitions to a state.

**Comment by oliver-diaz** [comment]
Hi Devin,

Th call to hesim is done within the execution of the function sample_pars from the package iviRA.
We will look into the source code of the latter to see I it can be modified to comply with the new version of hesim.
We will use the old version in the meantime.

Best
Oliver

**Comment by dincerti** [comment]
Hi Oliver,

Hi Oliver, hope you are doing well! The function should now work for you as it did in the previous version of hesim after commit 3330d10.
