### ISSUE TITLE
Several decision nodes

### ISSUE THREAD

**Issue by rucabe** [hesim-dev/hesim#15]
Hello,

I am wondering is it possible to create several decision nodes within the model? For example, two diagnostic strategies are compared, but within one strategy there is a consequent decision node on different types of surgeries. (Sorry for a silly question, I am new to R). Looking forward to your reply. 

P.S. thank you for a nice package.

**Comment by dincerti** [comment]
You  could set this up as a Markov model where there are states for different types of surgery.  The transition probabilities would vary by the two diagnostic strategies and for one of the strategies it would not be possible to transition to a surgery state. This would be similar to how the [hip replacement example](https://hesim-dev.github.io/hesim/articles/markov-inhomogeneous-cohort.html) is set up. Would that work for you?
