### ISSUE TITLE
Allow for survival models with flexible baseline hazards and frailties

### ISSUE THREAD

**Issue by bainman** [hesim-dev/hesim#49]
The **flexsurv** package used for the survival models in **hesim** has many nice features, including the **flexsurvspline** function that allow for flexible fit to the hazard. However, it does not allow for frailties, which are important when modeling multilevel survival data, such as data from multiple different clinical trials.  The **stan_surv** function of the **rstanarm** package can fit models with both a flexible baseline hazard and frailties.  Could **hesim** incorporate this functionality?

**Comment by dincerti** [comment]
Hi, `hesim` could incorporate this functionality. The difficulty would depend on the baseline hazard. If splines (e.g., M-splines, B-splines) were required, then it might take a little more work. Also, it doesn't look like `stan_surv()` is part of the master branch in `rstanarm` yet?

If you wanted to use a parametric baseline hazard (e.g., Weibull), then you might be able to input the parameter values manually into a `params_surv` object using the current package functionality. For instance, if the frailty term was capturing trial heterogeneity, then (I think) the frailty term could be absorbed into the intercept.

**Comment by dincerti** [comment]
Hi Brant,

Actually that can work with a really small tweak which I've pushed to the [stateprobs](https://github.com/hesim-dev/hesim/tree/stateprobs) branch and will add to the development branch once I've had a time to properly test it out.

Per `hesim 0.5.0`, you can store your predicted survival curves in a [`survival`](https://hesim-dev.github.io/hesim/reference/survival.html) object. I then created a `sim_stateprobs.survival()` function in the new branch which will compute state probabilities from the survival curves (like `Psm$sim_stateprobs()` currently does). You can then simply add the resulting `stateprobs` object to the `Psm` class object. Here is an example: 

```
library("data.table")
hesim_dat <- hesim_data(
  strategies = data.table(strategy_id = 1:2L, 
                          strategy2 = c(0, 1)),
  patients = data.table(patient_id = 1L, cons = 1),
  states = data.table(state_id = 1:2L,
                      state_name = c("Stable", "Progression"))
)

# Generate survival curves, you can do this however you want
params1 <- params_surv(
  coefs = list(rate = as.matrix(data.frame(
    cons = c(log(.2), log(.25)),
    strategy2 = c(log(.8), log(.9))
  ))),
  dist = "exp"
)
params2 <- params_surv(
  coefs = list(rate = as.matrix(data.frame(
    cons = c(log(.1), log(.15)),
    strategy2 = c(log(.8), log(.9))
  ))),
  dist = "exp"
)
params <- params_surv_list(params1, params2)
psm_curves <- create_PsmCurves(params, input_data = expand(hesim_dat))
surv <- psm_curves$survival(t = 0:20)

# Dummy utility model for example
utility_tbl <- stateval_tbl(
  data.table(state_id = 1:2,
             est = c(1, 1)
  ),
  dist = "fixed"
)
utilitymod <- create_StateVals(utility_tbl, 
                               hesim_data = hesim_dat,
                               n = 2)


# Compute state probabilities
stprobs <- sim_stateprobs(surv)

# Use Psm class to compute QALYs given state probabilities computed asbove
psm <- Psm$new(utility_model = utilitymod)
psm$stateprobs_ <- stprobs
psm$sim_qalys()
psm$qalys_
```

**Comment by bainman** [comment]
That sounds promising. I look forward to trying it out.

**Comment by dincerti** [comment]
@bainman the development version now supports this. You can construct a `survival` object with [`survival()`](https://hesim-dev.github.io/hesim/dev/reference/survival.html) and simulate state probabilities with [`sim_stateprobs.survival()`](https://hesim-dev.github.io/hesim/dev/reference/sim_stateprobs.survival.html). The `sim_stateprobs()` documentation provides an example of how to do this in the context of a partitioned survival analysis.

**Comment by bainman** [comment]
Terrific. I will check it out this week.
