### ISSUE TITLE
Method of moments SD or SE (mom_gamma)?

### ISSUE THREAD

**Issue by Healtheconomist** [hesim-dev/hesim#95]
Hi,

The HESIM mom_gamma function state that it uses the standard deviation as input to parametrise the gamma distribution. Should this be the standard error instead?

C

**Comment by dincerti** [comment]
Hi, `mom_gamma` computes the parameters of the gamma distribution given the mean and standard deviation of the underlying (assumed to be gamma) distribution. If the distribution of interest was the distribution of a parameter estimated via frequentist means, then its standard deviation could rightfully be called the standard error, but that is a particular case. So in my view, the standard deviation is the correct and more general term.
