### ISSUE TITLE
Is it possible to have mixed transitions from the same state?

### ISSUE THREAD

**Issue by mclements** [hesim-dev/hesim#96]
Devin,

Thank you for your very nice package.

We are interested in using individual-based CTSTMs modelling for relative survival -- that is, for background mortality using age (clock forward) as the primary time scale and for excess survival using time in state (clock reset) as the primary time scale. Is this possible using `reset_states` -- or does `reset_states` assume that _all_ transitions from a reset state are clock-reset? I should also ask: can we use relative survival models in `hesim`?

Sincerely, Mark Clements.

**Comment by dincerti** [comment]
Thank you for the kind words, Mark. 

The latter, unfortunately: all transitions from a reset state are assumed to be clock reset. Survival models that are supported are those documented [here](https://hesim-dev.github.io/hesim/reference/params_surv.html).
